/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		Aside: typeof import("./src/components/layout/aside/index.vue")["default"];
		ElAside: typeof import("element-plus/es")["ElAside"];
		ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
		ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
		ElButton: typeof import("element-plus/es")["ElButton"];
		ElCol: typeof import("element-plus/es")["ElCol"];
		ElContainer: typeof import("element-plus/es")["ElContainer"];
		ElDropdown: typeof import("element-plus/es")["ElDropdown"];
		ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
		ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
		ElFooter: typeof import("element-plus/es")["ElFooter"];
		ElForm: typeof import("element-plus/es")["ElForm"];
		ElFormItem: typeof import("element-plus/es")["ElFormItem"];
		ElHeader: typeof import("element-plus/es")["ElHeader"];
		ElIcon: typeof import("element-plus/es")["ElIcon"];
		ElImage: typeof import("element-plus/es")["ElImage"];
		ElInput: typeof import("element-plus/es")["ElInput"];
		ElMain: typeof import("element-plus/es")["ElMain"];
		ElMenu: typeof import("element-plus/es")["ElMenu"];
		ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
		ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
		ElPageHeader: typeof import("element-plus/es")["ElPageHeader"];
		ElPopover: typeof import("element-plus/es")["ElPopover"];
		ElResult: typeof import("element-plus/es")["ElResult"];
		ElRow: typeof import("element-plus/es")["ElRow"];
		ElSpace: typeof import("element-plus/es")["ElSpace"];
		ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
		ElTable: typeof import("element-plus/es")["ElTable"];
		ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
		ElTag: typeof import("element-plus/es")["ElTag"];
		Footer: typeof import("./src/components/layout/footer/index.vue")["default"];
		Header: typeof import("./src/components/layout/header/index.vue")["default"];
		Main: typeof import("./src/components/layout/main/index.vue")["default"];
		MenuTreeNode: typeof import("./src/components/layout/aside/menu-tree-node.vue")["default"];
		ProPage: typeof import("./src/components/pro/pro-page/index.vue")["default"];
		ProPageHeader: typeof import("./src/components/pro/pro-page-header/index.vue")["default"];
		ProPageMain: typeof import("./src/components/pro/pro-page-main/index.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
	}
	export interface ComponentCustomProperties {
		vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
	}
}
